### ISSUE TITLE
no error handling for wallpaperList

### ISSUE THREAD

**Issue by MaxG87** [denydias/kdesome#7]
In line 125 of the rc.lua, a random wallpaper is choosen. However, this list might be empty. This will lead to a state without window manager from which it is hard to recover.

A fix would be to check, whether there are wallpaper at all in the directory.

**Comment by denydias** [comment]
Thanks for reporting! It would be difficult to face this case, as my wallpaper directory always has something to show.

I'll fix that and let you know.

**Comment by denydias** [comment]
Done. Now it should handle an empty wallpaper table properly.

Also, it looks for JPG and PNG images only in the directory itself (as opposed to the recursive behavior from before this fix).

But there's a catch: the renamed `scanImg()` (it was `scanDir()`) do not check for an existing directory beforehand as Lua doesn't provide a platform independent way to do so. If the directory set in `wallpapers` variable doesn't not exist, there should be some error log message from `find` complaining about it, but awesome will not crash because of it anyway.
